---
- hosts: workstations
  become: true
  tasks:
    - name: " Start Httpd Service ( CentOs )"
      service: 
        name: httpd
        state: started
        enabled: yes
      when: 
        - ansible_distribution == "centos"
        - httpd.service.state != "running"
        - httpd.service.enabled == false


