---
- hosts: workstations
  become: true
  tasks:
    - name: change E-Mail Address for admin
      tags: apache,httpd,centos
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin Masoud@Email.com
      when: ansible_distribution = "CentOs"  
      register: httpd


    - name: " restart Httpd Service ( CentOs )"
      service: 
        name: httpd
        state: restarted
        enabled: yes
      when: 
        - httpd.change 


